---
name: ccp-template-org1
version: 1.0.0
client:
    organization: Org1
    credentialStore:
        path: './testdata/msp'
        cryptoStore:
            path: './testdata/msp'
    connection:
        timeout:
            peer:
                endorser: '300'
organizations:
    Org1:
        mspid: Org1MSP
        cryptoPath: fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/msp
        peers:
            - peer0.org1.example.com
        certificateAuthorities:
            - ca.org1.example.com
peers:
    peer0.org1.example.com:
        url: grpcs://localhost:7051
        tlsCACerts:
            path: fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/msp/cacerts/localhost-7054-ca-org1.pem

        grpcOptions:
            ssl-target-name-override: peer0.org1.example.com
            hostnameOverride: peer0.org1.example.com

certificateAuthorities:
    ca.org1.example.com:
        url: https://localhost:7054
        caName: ca-org1
        tlsCACerts:
            pem:
            path: fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/msp/cacerts/localhost-7054-ca-org1.pem
        httpOptions:
            verify: false
        registrar:
            enrollId: admin
            enrollSecret: adminpw
