email:
    dialer:
        server: example.com:587
        account: alice
        fromdom: org1.example.com
        todom: org2.example.com
        secret: secret
        template: To:%s\r\nSubject:[Cealgull] Verification Code\r\n\r\n%s\r\n
    redis:
        server: localhost:6379
        user: ''
        secret: ''
        db: 0
    template: The Verification Code is %06d.
    coderule: '[0-9]{6}'
    accrule: '[a-zA-Z0-9-_\.]{3-50}'
fabric:
    org: Org1
    cahost: ca.org1.example.com
    cacerts: './configs/ccp.yaml'
keyset:
    nr_mem: 64
    cap: 64
turnstile:
    secret: dummy
verify:
    server: localhost:8080
